apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
    - name: demo alerts
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: High Memory Usage
    - name: CPU
      rules:
      - alert: CPU idle warning
        expr: node_cpu_seconds_total{cpu="0", mode="idle"} > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: CPU is not idle
      - alert: CPU idle critical
        expr: node_cpu_seconds_total{cpu="0", mode="idle"} > 1000
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: CPU is not idle
    - name: Postgres
      rules:
      - alert: Postgres Down
        expr: pg_up == 0
        for: 5s
        labels:
          severity: critical
        annotations:
          summary: Postgres is down
      - alert: Postgres High Connections
        expr: pg_stat_activity_count{usename="postgres", state="active"} > 0
        for: 5s
        labels:
          severity: warning
        annotations:
          summary: Postgres has high connections

  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.monitoring.svc:9093"
    scrape_configs:
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_endpoints_name]
          regex: 'node-exporter'
          action: keep
      - job_name: 'postgres-exporter'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_endpoints_name]
          regex: 'postgres-exporter'
          action: keep